DynamicPortfolioSite.AdminUI/Models/ErrorViewModel.cs
using System;

namespace DynamicPortfolioSite.AdminUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DynamicPortfolioSite.AdminUI/Controllers/HomeController.cs
using DynamicPortfolioSite.AdminUI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace DynamicPortfolioSite.AdminUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DynamicPortfolioSite.AdminUI/ViewComponents/GetUserImgViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace DynamicPortfolioSite.AdminUI.ViewComponents
{
    [ViewComponent(Name = "GetUserImg")]
    public class GetUserImgViewComponent : ViewComponent
    {
        #region Ctor&Fields

        private readonly IConfiguration _config;

        public GetUserImgViewComponent(IConfiguration config)
        {
            _config = config;
        }

        #endregion

        public IViewComponentResult Invoke()
        {
            string image = _config.GetValue<string>("Defaults:DefaultUserImagePath");//default user image

            return View("Default", image);
        }
    }
}

DynamicPortfolioSite.AdminUI/Views/Shared/Components/GetUserImg/Default.cshtml
@model string
<a href="#" class="dropdown-toggle pr-0" data-toggle="dropdown">
    <img src="@Model" alt="user_auth" class="user-auth-img img-circle" />
    <span class="user-online-status"></span>
</a>

DynamicPortfolioSite.AdminUI/Views/Shared/TopMenuPartial.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="mobile-only-brand pull-left">
        <div class="nav-header pull-left">
            <div class="logo-wrap">
                <a href="@Url.Action("Index","Home")">
                    <img class="brand-img" src="~/template/img/logo.png" alt="brand" />
                    <span class="brand-text">@Localizer["TopMenuLogoTitle"]</span>
                </a>
            </div>
        </div>
        <a id="toggle_nav_btn" class="toggle-left-nav-btn inline-block ml-20 pull-left" href="javascript:void(0);"><i class="zmdi zmdi-menu"></i></a>
        <a id="toggle_mobile_search" data-toggle="collapse" data-target="#search_form" class="mobile-only-view" href="javascript:void(0);"><i class="zmdi zmdi-search"></i></a>
        <a id="toggle_mobile_nav" class="mobile-only-view" href="javascript:void(0);"><i class="zmdi zmdi-more"></i></a>
    </div>
    <div id="mobile_only_nav" class="mobile-only-nav pull-right">
        <ul class="nav navbar-right top-nav pull-right">
            <li class="dropdown auth-drp">
                @await Component.InvokeAsync("GetUserImg")
                <ul class="dropdown-menu user-auth-dropdown" data-dropdown-in="flipInX" data-dropdown-out="flipOutX">
                    <li>
                        <a asp-action="Profile" asp-controller="Account"><i class="zmdi zmdi-account"></i><span>@Localizer["TopMenuAccountProfile"]</span></a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a asp-action="Logout" asp-controller="Account"><i class="zmdi zmdi-power"></i><span>@Localizer["TopMenuAccountLogout"]</span></a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

DynamicPortfolioSite.AdminUI/Views/Shared/_Layout.cshtml
@{ Layout = null; }

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>@ViewData["Title"] - @Localizer["LayoutTitle"]</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="icon" href="~/template/img/logo.png" type="image/x-icon">
    @await RenderSectionAsync("Styles", required: false)

    <!-- Bootstrap table CSS -->
    <link href="~/template/vendors/bower_components/bootstrap-table/dist/bootstrap-table.css" rel="stylesheet" type="text/css" />

    <!-- Toast CSS -->
    <link href="~/template/vendors/bower_components/jquery-toast-plugin/dist/jquery.toast.min.css" rel="stylesheet" type="text/css">

    <!--alerts CSS -->
    <link href="~/template/vendors/bower_components/sweetalert/dist/sweetalert.css" rel="stylesheet" type="text/css">

    <!-- Data table CSS -->
    <link href="~/template/vendors/bower_components/datatables/media/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />

    <!-- Custom CSS -->
    <link href="~/template/dist/css/style.css" rel="stylesheet" type="text/css">

    <link href="~/css/main.css" rel="stylesheet" type="text/css">

</head>

<body>
    <!-- Preloader -->
    <div class="preloader-it">
        <div class="la-anim-1"></div>
    </div>

    <!-- /Preloader -->
    <div class="wrapper  theme-6-active pimary-color-pink">
        <!-- Top Menu Items -->
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="mobile-only-brand pull-left">
                <div class="nav-header pull-left">
                    <div class="logo-wrap">
                        <a href="@Url.Action("Index","Home")">
                            <img class="brand-img" src="~/template/img/logo.png" alt="brand" />
                            <span class="brand-text">Panel</span>
                        </a>
                    </div>
                </div>
                <a id="toggle_nav_btn" class="toggle-left-nav-btn inline-block ml-20 pull-left" href="javascript:void(0);"><i class="zmdi zmdi-menu"></i></a>
                <a id="toggle_mobile_search" data-toggle="collapse" data-target="#search_form" class="mobile-only-view" href="javascript:void(0);"><i class="zmdi zmdi-search"></i></a>
                <a id="toggle_mobile_nav" class="mobile-only-view" href="javascript:void(0);"><i class="zmdi zmdi-more"></i></a>
            </div>
            <div id="mobile_only_nav" class="mobile-only-nav pull-right">
                <ul class="nav navbar-right top-nav pull-right">
                    <li class="dropdown auth-drp">
                        @await Component.InvokeAsync("GetUserImg")
                        <ul class="dropdown-menu user-auth-dropdown" data-dropdown-in="flipInX" data-dropdown-out="flipOutX">
                            <li>
                                <a asp-action="Profile" asp-controller="Account"><i class="zmdi zmdi-account"></i><span>Hesap Ayarları</span></a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a asp-action="Logout" asp-controller="Account"><i class="zmdi zmdi-power"></i><span>Çıkış</span></a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- /Top Menu Items -->
        <!-- Left Sidebar Menu -->
        <partial name="_LeftMenuPartial" />
        <!-- /Left Sidebar Menu -->
        <!-- Main Content -->
        <div class="page-wrapper">
            <div class="container-fluid pt-25">
                @RenderBody()
            </div>

            <!-- Footer -->
            <footer class="footer container-fluid pl-30 pr-30">
                <div class="row">
                    <div class="col-sm-12">
                        <p>@DateTime.Now.Year &copy; - @Localizer["LayoutTitle"]</p>
                    </div>
                </div>
            </footer>
            <!-- /Footer -->

        </div>
        <!-- /Main Content -->

    </div>
    <!-- /#wrapper -->
    <!-- JavaScript -->
    <script src="@Url.Content("~/bundles/js/bundle.min.js")" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

DynamicPortfolioSite.AdminUI/Views/Shared/_LeftMenuPartial.cshtml
<div class="fixed-sidebar-left">
    <ul class="nav navbar-nav side-nav nicescroll-bar">
        <li class="navigation-header">
            <span>System</span>
            <i class="zmdi zmdi-more"></i>
        </li>
        <li>
            <a href="@Url.Action("Index","Settings")">
                <div class="pull-left">
                    <i class="zmdi zmdi-settings mr-20"></i>
                    <span class="right-nav-text">Settings</span>
                </div>
                <div class="clearfix"></div>
            </a>
        </li>

    </ul>
</div>