DynamicPortfolioSite.WebUI/Models/ErrorViewModel.cs
using System;

namespace DynamicPortfolioSite.WebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DynamicPortfolioSite.WebUI/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace DynamicPortfolioSite.WebUI.Controllers
{
    public class ErrorController : Controller
    {
        #region Ctor&Fields

        private readonly ILogger<ErrorController> _logger;

        public ErrorController(ILogger<ErrorController> logger)
        {
            _logger = logger;
        }

        #endregion

        public IActionResult Index()
        {
            return View();
        }
    }
}

DynamicPortfolioSite.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace DynamicPortfolioSite.WebUI.Controllers
{
    public class HomeController : Controller
    {
        #region Ctor&Fields

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        #endregion

        public IActionResult Index()
        {
            return View();
        }

    }
}

DynamicPortfolioSite.WebUI/ViewComponents/AboutSlideViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace DynamicPortfolioSite.WebUI.ViewComponents
{
    [ViewComponent(Name = "AboutSlide")]
    public class AboutSlideViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

DynamicPortfolioSite.WebUI/ViewComponents/BlogPostSlideViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace DynamicPortfolioSite.WebUI.ViewComponents
{
    [ViewComponent(Name = "BlogPostSlide")]
    public class BlogPostSlideViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

DynamicPortfolioSite.WebUI/ViewComponents/ContactSlideViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace DynamicPortfolioSite.WebUI.ViewComponents
{
    [ViewComponent(Name = "ContactSlide")]
    public class ContactSlideViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }

    }
}

DynamicPortfolioSite.WebUI/ViewComponents/HomeSlideViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace DynamicPortfolioSite.WebUI.ViewComponents
{
    [ViewComponent(Name = "HomeSlide")]
    public class HomeSlideViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

DynamicPortfolioSite.WebUI/ViewComponents/NavAndLogoViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace DynamicPortfolioSite.WebUI.ViewComponents
{
    [ViewComponent(Name = "NavAndLogo")]
    public class NavAndLogoViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

DynamicPortfolioSite.WebUI/ViewComponents/ProjectsSlideViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace DynamicPortfolioSite.WebUI.ViewComponents
{
    [ViewComponent(Name = "ProjectsSlide")]
    public class ProjectsSlideViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

DynamicPortfolioSite.WebUI/ViewComponents/SeoTagsViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace DynamicPortfolioSite.WebUI.ViewComponents
{
    [ViewComponent(Name = "SeoTags")]
    public class SeoTagsViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

DynamicPortfolioSite.WebUI/Views/Home/Index.cshtml
@{
}

@await Component.InvokeAsync("NavAndLogo")

<div class="slides">
    @*  Home  *@
    <div class="slide" id="1">
        <div class="content first-content">
            <div class="container-fluid">
                @await Component.InvokeAsync("HomeSlide")
            </div>
        </div>
    </div>
    @*  Hakkımda  *@
    <div class="slide" id="2">
        <div class="content second-content">
            <div class="container-fluid">
                @await Component.InvokeAsync("AboutSlide")
            </div>
        </div>
    </div>
    @* Blog Post (Medium Link)  *@
    <div class="slide" id="3">
        <div class="content third-content">
            <div class="container-fluid">
                @await Component.InvokeAsync("BlogPostSlide")
            </div>
        </div>
    </div>
    @* Projelerim  *@
    <div class="slide" id="4">
        <div class="content fourth-content">
            <div class="container-fluid">
                @await Component.InvokeAsync("ProjectsSlide")
            </div>
        </div>
    </div>
    @* İletişim *@
    <div class="slide" id="5">
        <div class="content fifth-content">
            <div class="container-fluid">
                @await Component.InvokeAsync("ContactSlide")
            </div>
        </div>
    </div>

</div>

DynamicPortfolioSite.WebUI/Views/Shared/Components/AboutSlide/Default.cshtml
<div class="col-md-6">
    <div class="left-content">

        @*@Html.Raw(Model.AboutText)*@

    </div>
</div>
<div class="col-md-6">
    <div class="right-image">

        <img src="img/about_image.jpg" alt="">
    </div>
</div>

DynamicPortfolioSite.WebUI/Views/Shared/Components/BlogPostSlide/Default.cshtml
<div class="col-md-12">
    <div class="row">
        <div class="first-section">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <div class="left-content">
                            <h2>Quisque commodo quam</h2>
                            <p>Vestibulum augue ex, finibus sit amet nisi id, maximus ultrices ipsum. Maecenas rhoncus nibh in mauris lobortis, a maximus diam faucibus. In et eros urna. Suspendisse potenti. Pellentesque commodo, neque nec molestie tempus, purus ante feugiat augue.</p>
                            <div class="main-btn"><a href="#4">Continue Reading</a></div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="right-image">
                            <img src="img/first_service.jpg" alt="first service">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="second-section">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <div class="left-image">
                            <img src="img/second_service.jpg" alt="second service">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="right-content">
                            <h2>Maecenas eu purus eu sapien</h2>
                            <p>Sed vitae felis in lorem mollis mollis eget in leo. Donec commodo, ex nec rutrum venenatis, nisi nisl malesuada magna, sed semper ipsum enim a ipsum. Aenean in ante vel mi molestie bibendum. Quisque sit amet lacus in diam pretium faucibus. Cras vel justo lorem.</p>
                            <div class="main-btn"><a href="#4">Continue Reading</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DynamicPortfolioSite.WebUI/Views/Shared/Components/ContactSlide/Default.cshtml
@*@model ContactModel*@

<div class="col-md-6">
    <div id="map">
        <!-- How to change your own map point
                1. Go to Google Maps
                2. Click on your location point
                3. Click "Share" and choose "Embed map" tab
                4. Copy only URL and paste it within the src="" field below
        -->
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3647.3030413476204!2d100.5641230193719!3d13.757206847615207!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xf51ce6427b7918fc!2sG+Tower!5e0!3m2!1sen!2sth!4v1510722015945" width="100%" height="500px" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
</div>
@*<div class="col-md-6">
    <form id="contact" asp-action="SendMessage" method="post">
        <div class="row">
            <div class="col-md-12">
                <fieldset>
                    <input asp-for="Name" type="text" class="form-control" placeholder="İsminiz.." required="">
                </fieldset>
            </div>
            <div class="col-md-12">
                <fieldset>
                    <input asp-for="Email" type="email" class="form-control" placeholder="E-Posta Adresiniz.." required="">
                </fieldset>
            </div>
            <div class="col-md-12">
                <fieldset>
                    <input asp-for="Subject" type="text" class="form-control" placeholder="Konu" required="">
                </fieldset>
            </div>
            <div class="col-md-12">
                <fieldset>
                    <textarea asp-for="Text" rows="6" class="form-control" placeholder="Mesajınız..." required=""></textarea>
                </fieldset>
            </div>
            <div class="col-md-12">
                <fieldset>
                    <button type="submit" id="form-submit" class="btn">Gönder</button>
                </fieldset>
            </div>
        </div>
    </form>
</div>*@

DynamicPortfolioSite.WebUI/Views/Shared/Components/NavAndLogo/Default.cshtml
<nav>
    <div class="logo">
        <img src="img/logo.png" alt="">
        @*<img src="@Model.LogoImgUrl" alt="" style="width:250px !important;height:55px !important" />*@
    </div>
    <div class="mini-logo">
        <img src="img/mini_logo.png" alt="">
        @*<img src="~/img/NewFolder/logo1mini.png" style="width:50px !important;height:50px !important" />*@
    </div>
    <ul>
        <li><a href="#1"><i class="fa fa-home"></i> <em>@Localizer["NavSlideHome"]</em></a></li>
        <li><a href="#2"><i class="fa fa-user"></i> <em>@Localizer["NavSlideAbout"]</em></a></li>
        <li><a href="#3"><i class="fa fa-pencil"></i> <em>@Localizer["NavSlideBlog"]</em></a></li>
        <li><a href="#4"><i class="fa fa-image"></i> <em>@Localizer["NavSlideProjects"]</em></a></li>
        <li><a href="#5"><i class="fa fa-envelope"></i> <em>@Localizer["NavSlideContact"]</em></a></li>
    </ul>
</nav>

DynamicPortfolioSite.WebUI/Views/Shared/Components/ProjectsSlide/Default.cshtml
<div class="row">
    @*@if (Model.works != null)
    {
        @foreach (var work in Model.works)
        {
            <div class="col-md-4 col-sm-6">
                <div class="item">
                    <div class="thumb">
                        <a href="@work.ProfileImg" data-lightbox="image-1">
                            <div class="hover-effect">
                                <div class="hover-content">
                                    <h2>@work.Title</h2>
                                    <p>@work.Description</p>
                                </div>
                            </div>
                        </a>
                        <div class="image">
                            <img src="@work.ProfileImg">
                        </div>
                    </div>
                </div>
            </div>}}*@
</div>

DynamicPortfolioSite.WebUI/Views/Shared/Components/SeoTags/Default.cshtml
<title>Model.WebSiteTitile</title>
<meta name="description" content="Model.SeoMetaDescription">
<meta name="keywords" content="Model.SeoMetaKeywords" />
<link rel="shortcut icon" type="image/png" href="Model.IconUrl" />

DynamicPortfolioSite.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    @await Component.InvokeAsync("SeoTags")

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="@Url.Content("~/bundles/css/bundle.min.css")" asp-append-version="true" />

    <script src="js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>

    @await RenderSectionAsync("Styles", required: false)

</head>

<body>

    <div class="sequence">

        <div class="seq-preloader">
            <svg width="39" height="16" viewBox="0 0 39 16" xmlns="http://www.w3.org/2000/svg" class="seq-preload-indicator"><g fill="#F96D38"><path class="seq-preload-circle seq-preload-circle-1" d="M3.999 12.012c2.209 0 3.999-1.791 3.999-3.999s-1.79-3.999-3.999-3.999-3.999 1.791-3.999 3.999 1.79 3.999 3.999 3.999z" /><path class="seq-preload-circle seq-preload-circle-2" d="M15.996 13.468c3.018 0 5.465-2.447 5.465-5.466 0-3.018-2.447-5.465-5.465-5.465-3.019 0-5.466 2.447-5.466 5.465 0 3.019 2.447 5.466 5.466 5.466z" /><path class="seq-preload-circle seq-preload-circle-3" d="M31.322 15.334c4.049 0 7.332-3.282 7.332-7.332 0-4.049-3.282-7.332-7.332-7.332s-7.332 3.283-7.332 7.332c0 4.05 3.283 7.332 7.332 7.332z" /></g></svg>
        </div>

    </div>

    @RenderBody()

    <div class="footer">
        <div class="content">
            <p>Copyright &copy; @DateTime.Now.Year - Fatih Dumlupınar</p>
        </div>
    </div>

    <script src="@Url.Content("~/bundles/js/bundle.min.js")" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>